FROM alpine:3 as build
ARG PLUGIN_MODULE=github.com/cnmaple/yzj-api-decryption
ARG PLUGIN_GIT_REPO=https://github.com/cnmaple/yzj-api-decryption.git
ARG PLUGIN_GIT_BRANCH=master
RUN apk add --update git && \
    git clone ${PLUGIN_GIT_REPO} /plugins-local/src/${PLUGIN_MODULE} \
      --depth 1 --single-branch --branch ${PLUGIN_GIT_BRANCH}

FROM traefik:v2.8.7
COPY --from=build /plugins-local /plugins-local